version: '3.8'

services:
  mysqldb:
    container_name: mysqldb
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER:root
      - MYSQL_PASSWORD:root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=foyerDB
    volumes:
      - db_vol:/var/lib/mysqldb

  foyer-app:
    image: fardi1312/foyerdevops:latest
    restart: unless-stopped
    build: ./
    ports:
      - "8111:8111"
    depends_on:
      - mysqldb
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - "8888:80"
    environment:
      - PMA_HOST=mysqldb
      - PMA_USER=root
      - PMA_PASSWORD=root
    depends_on:
      - mysqldb
volumes:
  db_vol: