version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: foyer
      MYSQL_USER: utilisateur
      MYSQL_PASSWORD: motdepasse
    ports:
      - "3306:3306"  # Host port mapped to container port
    networks:
      - app-network
    volumes:
      - mysql-data:/var/lib/mysql  # Persist MySQL data

  spring-app:
    image: fardi1312/foyerdevops:latest
    build:
      context: .  # Looks for Dockerfile in the current directory
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/foyer  # Internal MySQL container connection
      SPRING_DATASOURCE_USERNAME: utilisateur
      SPRING_DATASOURCE_PASSWORD: motdepasse
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SERVER_PORT: 8087
      SERVER_SERVLET_CONTEXT_PATH: /Foyer

    ports:
      - "8111:8087"
    depends_on:
      - mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8887:80"  # Change to desired host port
    environment:
      PMA_HOST: mysql
      PMA_USER: utilisateur
      PMA_PASSWORD: motdepasse
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data: