version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: foyerMassoudFardi
      MYSQL_USER: utilisateur
      MYSQL_PASSWORD: motdepasse
    ports:
      - "3307:3306"  # Change host port to 3307
    networks:
      - app-network
    volumes:
      - mysql-data:/var/lib/mysql # Persist MySQL data

  spring-app:
    image: fardi1312/foyerdokerhub:${BUILD_NUMBER} # Use your Docker Hub username and Jenkins BUILD_NUMBER for tagging
    build:
      context: . # This will look for a Dockerfile in the current directory
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/foyerMassoudFardi  # Keep using 3306 inside the container
      SPRING_DATASOURCE_USERNAME: utilisateur
      SPRING_DATASOURCE_PASSWORD: motdepasse
    ports:
      - "8412:8412"
    depends_on:
      - mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data: # Named volume for MySQL data persistence
