services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: foyerMassoudFardi
      MYSQL_USER: utilisateur
      MYSQL_PASSWORD: motdepasse
    ports:
      - "3310:3306"
    networks:
      - app-network
    volumes:
      - mysql-data:/var/lib/mysql

  spring-app:
    image: fardi1312/foyerdokerhub:latest
    build:
      context: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/foyerMassoudFardi
      SPRING_DATASOURCE_USERNAME: utilisateur
      SPRING_DATASOURCE_PASSWORD: motdepasse
    ports:
      - "8412:8081"
    depends_on:
      - mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8888:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: utilisateur
      PMA_PASSWORD: motdepasse
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
